apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: simple-task-run-
spec:
  taskSpec:
    steps:
      - name: param-substitution-test
        ref:
          name: simple-step-action
        params:
          - name: param1
            value: "Value for Param 1"
      - name: param-substitution-test-2
        ref:
          name: simple-step-action
        params:
          - name: param1
            value: "Value for Param 1"
          - name: param2
            value: "Value for Param 2"
